apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Salwan-Mohamed/gitops-mastery-tutorial
    targetRevision: main
    path: part-03-gitops-at-scale/01-app-of-apps/basic-example/apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
