apiVersion: v1
kind: Service
metadata:
  name: my-weather-app-service
  labels:
    app: weather
    app.kubernetes.io/name: weather-app
    app.kubernetes.io/part-of: gitops-demo
spec:
  type: ClusterIP
  selector:
    app: weather
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  sessionAffinity: None
