{{- if .Values.secrets.DATABASE_PASSWORD }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "my-nodejs-app.fullname" . }}-secret
  labels:
    {{- include "my-nodejs-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{- if $value }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
{{- end }}