apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: ecommerce
    component: frontend
spec:
  selector:
    app: ecommerce
    component: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: http
  type: ClusterIP